spring.application.name=emprendedoresucc
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://andressebastiansuarezcastano_db_user:mWMuYBk67cgs91lU@emprendedoresucc-cluste.fppdwt2.mongodb.net/emprendedoresucc}

# CONFIGURACIÓN DE CORREO (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=andressebastiansuarezcastano@gmail.com
spring.mail.password=ynbamdpwjiaaqrio
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
